### ISSUE TITLE
Crash on reading large objects

### ISSUE THREAD

**Issue by gCurtisCT** [kriskowal/q-io#137]
I'm trying to read a 640mb file using `read()`, and it crashes.

```
C:\Users\Jim\Desktop\video ingest\node_modules\q\q.js:128
                    throw e;
                          ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at Function.join (C:\Users\Jim\Desktop\video ingest\node_modules\q-io\reader.js:123:14)
    at slurp (C:\Users\Jim\Desktop\video ingest\node_modules\q-io\reader.js:49:39)
    at C:\Users\Jim\Desktop\video ingest\node_modules\q-io\reader.js:64:30
    at _fulfilled (C:\Users\Jim\Desktop\video ingest\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (C:\Users\Jim\Desktop\video ingest\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\Users\Jim\Desktop\video ingest\node_modules\q\q.js:756:13
)
    at C:\Users\Jim\Desktop\video ingest\node_modules\q\q.js:564:44
    at flush (C:\Users\Jim\Desktop\video ingest\node_modules\q\q.js:110:17)
    at process._tickDomainCallback (node.js:459:13)
```

Is there anything I can do to avoid this?

**Comment by kriskowal** [comment]
You will probably need to appeal to a lower level API, or find a way to operate on your data as a stream instead of bringing it all into memory. There may be a memory leak inherent to Q-IO, so if you can get a heap dump and track down the objects, it might be helpful toward finding a fix.

I would be happy to enable you to fix Q-IO if you isolate the problem.
